# @package eval.my.metrics.forget_Q_A_Prob
defaults:
  - ../../data/datasets@datasets: my_forget
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: probability
batch_size: ${eval.my.batch_size}
split_by_language: true
